services:
  - type: web
    name: mochi-personal-finance-api
    runtime: image
    plan: free
    image:
      url: docker.io/trietdang5599/mochi-finance-api:latest
    healthCheckPath: /docs
    envVars:
      - key: APP_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: GOOGLE_DRIVE_FILE_ID
        sync: false
